version: "3"
networks:
  my-nwtwoek:
    driver: bridge
services:
  security_gateway:
    # restart: always
    build:
      dockerfile: nginx/Dockerfile
      # dockerfile: Dockerfile.dev
      context: ./security_gateway
    ports:
      - "8086:8086"
    # command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - my-nwtwoek
  backend_side:
    # restart: always
    build:
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
      context: ./backend_side/nginx
    ports:
      - "8087:8087"
    # command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - my-nwtwoek
