version: "3"
networks:
  vf-uk-configuration-portal:
    driver: bridge
services:
  security_gateway:
    # restart: always
    build:
      dockerfile: nginx/Dockerfile
      # dockerfile: Dockerfile.dev
      context: ./security_gateway
    ports:
      - "8086:8086"
    # command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - vf-uk-configuration-portal
  apix_server:
    # restart: always
    build:
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
      context: ./apix_server/nginx
    ports:
      - "8087:8087"
    command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - vf-uk-configuration-portal
