version: "3"
networks:
  vf-uk-configuration-portal:
    driver: bridge
services:
  nginx_gateway:
    # restart: always
    build:
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8086:8086"
    # command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - vf-uk-configuration-portal
  nginx_apix:
    # restart: always
    build:
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
      context: ../apix_server/nginx
    ports:
      - "8087:8087"
    command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - vf-uk-configuration-portal
