# FROM nginx
# COPY ./rawheader_logging.conf /etc/nginx/conf.d/default.conf
# CMD ["nginx", "-g", "daemon off;"]
FROM nginx
EXPOSE 8087
RUN nginx -v
COPY nginx.conf /etc/nginx/nginx.conf
COPY logging.js /etc/nginx/logging.js
